import { jsPDF } from 'jspdf'

const TEAL = [13, 148, 136]   // #0D9488
const DARK = [26, 26, 26]     // #1A1A1A
const GRAY = [107, 114, 128]  // #6B7280
const PAGE_W = 210 // A4 mm
const PAGE_H = 297
const MARGIN = 20
const CONTENT_W = PAGE_W - 2 * MARGIN

// Replace Unicode characters that jsPDF can't render with ASCII equivalents
function sanitize(text) {
  if (!text) return ''
  return text
    .replace(/≥/g, '>=')
    .replace(/≤/g, '<=')
    .replace(/²/g, '2')
    .replace(/³/g, '3')
    .replace(/°/g, ' deg')
    .replace(/±/g, '+/-')
    .replace(/—/g, ' - ')
    .replace(/–/g, '-')
    .replace(/'/g, "'")
    .replace(/'/g, "'")
    .replace(/"/g, '"')
    .replace(/"/g, '"')
    .replace(/·/g, '-')
    .replace(/…/g, '...')
    .replace(/\u00A0/g, ' ') // non-breaking space
}

function addFooter(doc, pageNum) {
  doc.setFontSize(8)
  doc.setTextColor(...GRAY)
  doc.text(sanitize(`Generated by Middle Out  |  ${new Date().toLocaleDateString('en-SG')}`), MARGIN, PAGE_H - 12)
  doc.text(`${pageNum}`, PAGE_W - MARGIN, PAGE_H - 12, { align: 'right' })
}

function addAccentBar(doc, y) {
  doc.setFillColor(...TEAL)
  doc.rect(MARGIN, y, CONTENT_W, 1.5, 'F')
}

// Render a chart to a canvas and return as data URL
async function renderChartImage(data, chartType = 'line', label = '', unit = '') {
  const { toPng } = await import('html-to-image')

  // Create a hidden container
  const container = document.createElement('div')
  container.style.cssText = 'position:absolute;left:-9999px;top:0;width:700px;height:320px;background:#fff;'
  document.body.appendChild(container)

  // Use a canvas-based approach: draw the chart manually
  const canvas = document.createElement('canvas')
  canvas.width = 1400  // 2x for retina
  canvas.height = 640
  canvas.style.width = '700px'
  canvas.style.height = '320px'
  const ctx = canvas.getContext('2d')

  // Background
  ctx.fillStyle = '#FFFFFF'
  ctx.fillRect(0, 0, 1400, 640)

  if (!data || data.length === 0) {
    document.body.removeChild(container)
    return null
  }

  const padding = { top: 50, right: 60, bottom: 70, left: 80 }
  const chartW = 1400 - padding.left - padding.right
  const chartH = 640 - padding.top - padding.bottom

  const values = data.map(d => d.value)
  const minVal = Math.min(...values)
  const maxVal = Math.max(...values)
  const valRange = maxVal - minVal || 1
  const yPad = valRange * 0.1
  const yMin = Math.max(0, minVal - yPad)
  const yMax = maxVal + yPad

  // Helper to convert data to pixel coords
  const toX = (i) => padding.left + (i / (data.length - 1)) * chartW
  const toY = (v) => padding.top + chartH - ((v - yMin) / (yMax - yMin)) * chartH

  // Grid lines
  ctx.strokeStyle = '#E5E7EB'
  ctx.lineWidth = 1
  const gridLines = 5
  for (let i = 0; i <= gridLines; i++) {
    const gy = padding.top + (i / gridLines) * chartH
    ctx.beginPath()
    ctx.moveTo(padding.left, gy)
    ctx.lineTo(1400 - padding.right, gy)
    ctx.stroke()

    // Y-axis labels
    const val = yMax - (i / gridLines) * (yMax - yMin)
    ctx.fillStyle = '#6B7280'
    ctx.font = '22px monospace'
    ctx.textAlign = 'right'
    ctx.fillText(val.toFixed(val >= 100 ? 0 : 1), padding.left - 10, gy + 7)
  }

  // X-axis labels
  ctx.textAlign = 'center'
  ctx.fillStyle = '#6B7280'
  ctx.font = '22px monospace'
  const labelStep = Math.max(1, Math.floor(data.length / 8))
  for (let i = 0; i < data.length; i += labelStep) {
    const x = toX(i)
    ctx.fillText(String(data[i].year), x, 640 - padding.bottom + 35)
  }
  // Always show last year
  if (data.length > 1) {
    ctx.fillText(String(data[data.length - 1].year), toX(data.length - 1), 640 - padding.bottom + 35)
  }

  if (chartType === 'bar') {
    // Bar chart
    const barW = Math.max(8, (chartW / data.length) * 0.6)
    for (let i = 0; i < data.length; i++) {
      const x = toX(i) - barW / 2
      const y = toY(data[i].value)
      const h = padding.top + chartH - y
      ctx.fillStyle = '#0D9488'
      ctx.beginPath()
      ctx.roundRect(x, y, barW, h, 4)
      ctx.fill()
    }
  } else {
    // Line chart
    ctx.strokeStyle = '#0D9488'
    ctx.lineWidth = 4
    ctx.lineJoin = 'round'
    ctx.lineCap = 'round'
    ctx.beginPath()
    for (let i = 0; i < data.length; i++) {
      const x = toX(i)
      const y = toY(data[i].value)
      if (i === 0) ctx.moveTo(x, y)
      else ctx.lineTo(x, y)
    }
    ctx.stroke()

    // Dots
    for (let i = 0; i < data.length; i++) {
      const x = toX(i)
      const y = toY(data[i].value)
      ctx.fillStyle = '#FFFFFF'
      ctx.beginPath()
      ctx.arc(x, y, 6, 0, Math.PI * 2)
      ctx.fill()
      ctx.fillStyle = '#0D9488'
      ctx.beginPath()
      ctx.arc(x, y, 4, 0, Math.PI * 2)
      ctx.fill()
    }
  }

  // Title
  ctx.fillStyle = '#1A1A1A'
  ctx.font = 'bold 26px sans-serif'
  ctx.textAlign = 'left'
  ctx.fillText(sanitize(`${label}${unit ? ` (${unit})` : ''}`), padding.left, 30)

  const dataUrl = canvas.toDataURL('image/jpeg', 0.9)
  document.body.removeChild(container)
  return dataUrl
}

export async function generateReport({ healthData, profile, insight, selectedIndicators }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let pageNum = 1

  // ── Cover Page ──
  addAccentBar(doc, 40)
  doc.setFontSize(36)
  doc.setTextColor(...DARK)
  doc.text('Middle Out', MARGIN, 58)
  doc.setFontSize(16)
  doc.setTextColor(...GRAY)
  doc.text('Singapore Health Snapshot', MARGIN, 68)

  doc.setFontSize(11)
  doc.setTextColor(...DARK)
  doc.text(sanitize(`Generated ${new Date().toLocaleDateString('en-SG', { day: 'numeric', month: 'long', year: 'numeric' })}`), MARGIN, 85)

  if (profile) {
    doc.setFontSize(10)
    doc.setTextColor(...GRAY)
    const parts = []
    if (profile.gender) parts.push(profile.gender)
    if (profile.age) parts.push(`Age ${profile.age}`)
    if (profile.ethnicity) parts.push(profile.ethnicity)
    if (parts.length) doc.text(sanitize(`Profile: ${parts.join(' | ')}`), MARGIN, 93)
  }

  addFooter(doc, pageNum)

  // ── Executive Summary ──
  doc.addPage()
  pageNum++
  addAccentBar(doc, 25)

  doc.setFontSize(20)
  doc.setTextColor(...DARK)
  doc.text('Key Indicators at a Glance', MARGIN, 40)

  const summaryStats = [
    { label: 'Life Expectancy', key: 'life_expectancy', format: v => `${v} years` },
    { label: 'Fertility Rate', key: 'total_fertility_rate', format: v => `${v} births/woman` },
    { label: 'Diabetes Prevalence', key: 'diabetes_prevalence', format: v => `${v}%` },
    { label: 'Aged 65+', key: 'aged_65_plus', format: v => `${v}%` },
    { label: 'Daily Smoking', key: 'daily_smoking_rate', format: v => `${v}%` },
    { label: 'Govt Health Spend', key: 'govt_health_expenditure', format: v => `S$${v}B` },
  ]

  let y = 52
  doc.setFontSize(10)
  for (const stat of summaryStats) {
    const indicator = healthData?.[stat.key]
    if (!indicator?.data?.length) continue
    const latest = indicator.data[indicator.data.length - 1]

    doc.setTextColor(...DARK)
    doc.setFont('helvetica', 'bold')
    doc.text(stat.label, MARGIN, y)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...TEAL)
    doc.text(stat.format(latest.value), MARGIN + 60, y)

    doc.setTextColor(...GRAY)
    doc.text(`(${latest.year})`, MARGIN + 100, y)

    y += 10
  }

  addFooter(doc, pageNum)

  // ── Selected Indicator Pages (with charts) ──
  if (selectedIndicators?.length) {
    for (const key of selectedIndicators) {
      const indicator = healthData?.[key]
      if (!indicator?.data?.length) continue

      doc.addPage()
      pageNum++
      addAccentBar(doc, 25)

      // Title
      doc.setFontSize(18)
      doc.setTextColor(...DARK)
      doc.text(sanitize(indicator.label), MARGIN, 40)

      // Description
      let contentY = 48
      if (indicator.description) {
        doc.setFontSize(9)
        doc.setTextColor(...GRAY)
        doc.setFont('helvetica', 'normal')
        const descLines = doc.splitTextToSize(sanitize(indicator.description), CONTENT_W)
        doc.text(descLines, MARGIN, contentY)
        contentY += descLines.length * 4.5 + 6
      }

      // Determine chart type
      const isBar = ['govt_health_expenditure', 'hospital_beds', 'psychiatric_admissions'].includes(key)

      // Render chart image
      try {
        const chartImg = await renderChartImage(
          indicator.data,
          isBar ? 'bar' : 'line',
          indicator.label,
          indicator.unit
        )
        if (chartImg) {
          const imgW = CONTENT_W
          const imgH = imgW * (320 / 700) // maintain aspect ratio
          doc.addImage(chartImg, 'JPEG', MARGIN, contentY, imgW, imgH)
          contentY += imgH + 8
        }
      } catch (err) {
        console.error('Chart render failed for', key, err)
        contentY += 5
      }

      // Latest value callout
      const latest = indicator.data[indicator.data.length - 1]
      if (contentY < PAGE_H - 50) {
        doc.setFillColor(240, 253, 250)
        doc.roundedRect(MARGIN, contentY, CONTENT_W, 14, 3, 3, 'F')
        doc.setFontSize(11)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...TEAL)
        doc.text(sanitize(`Latest: ${latest.value} ${indicator.unit || ''} (${latest.year})`), MARGIN + 5, contentY + 9)
        contentY += 20
      }

      // Source
      if (indicator.source) {
        doc.setFontSize(8)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...GRAY)
        doc.text(sanitize(`Source: ${indicator.source}`), MARGIN, PAGE_H - 20)
      }

      addFooter(doc, pageNum)
    }
  }

  // ── Personal Insight Page ──
  if (insight) {
    doc.addPage()
    pageNum++
    addAccentBar(doc, 25)

    doc.setFontSize(18)
    doc.setTextColor(...DARK)
    doc.text('Your Personal Insight', MARGIN, 40)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)

    // Strip markdown formatting and sanitize for PDF
    const cleanText = sanitize(
      insight
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .replace(/#{1,3}\s/g, '')
    )

    const lines = doc.splitTextToSize(cleanText, CONTENT_W)
    let textY = 50
    for (const line of lines) {
      if (textY > PAGE_H - 30) {
        addFooter(doc, pageNum)
        doc.addPage()
        pageNum++
        textY = 30
      }
      doc.text(line, MARGIN, textY)
      textY += 5
    }

    doc.setFontSize(8)
    doc.setTextColor(...GRAY)
    doc.text('AI-generated insight based on population health data. Not personal medical advice.', MARGIN, PAGE_H - 20)
    addFooter(doc, pageNum)
  }

  doc.save('middleout-health-snapshot.pdf')
}
